### ISSUE TITLE
BATCH_JOB_QUEUE_ARN is a object at handler.py

### ISSUE THREAD

**Issue by PauloCarneiro99** [ikedaosushi/serverless-batch-example#1]
I was trying this code and when I invoke the lambda handler.py the submit_job got an error message. This is caused by BATCH_JOB_QUEUE_ARN being an object. I fix this by passing the BATCH_JOB_QUEUE_NAME and using boto3 lib to get this queue ARN.

At handler.py
```python
client = boto3.client("batch")
BATCH_JOB_QUEUE_NAME = os.environ.get("BATCH_JOB_QUEUE_NAME")
BATCH_JOB_QUEUE_ARN = client.describe_job_queues(jobQueues=[BATCH_JOB_QUEUE_NAME])["jobQueues"][0]["jobQueueArn"]
```

At serverless.yml
```yaml
  environment:
    BATCH_JOB_QUEUE_NAME: ${self:custom.batch.job_queue}
    BATCH_JOB_DEFINITION: ${self:custom.batch.job_definition}
```
